# Generated by Django 5.0.6 on 2024-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
